apiVersion: apps/v1
kind: Deployment

metadata:
  name: document-analyzer
  namespace: miniproject-management

spec:
  replicas: 2

  selector:
    matchLabels:
      app: document-analyzer

  template:
    metadata:
      labels:
        app: document-analyzer

    spec:
      containers:
        - name: document-analyzer

          image: 804540872991.dkr.ecr.ap-northeast-2.amazonaws.com/miniproject-management/document-analyzer:latest

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: AWS_REGION
              value: ap-northeast-2

            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: S3_BUCKET_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: AWS_SECRET_ACCESS_KEY

          readinessProbe:
            httpGet:
              path: /health
              port: 8080

          livenessProbe:
            httpGet:
              path: /health
              port: 8080