apiVersion: apps/v1
kind: Deployment

metadata:
  name: document-analyzer
  namespace: miniproject-management

spec:
  replicas: 2

  selector:
    matchLabels:
      app: document-analyzer

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: document-analyzer

    spec:
      containers:
        - name: document-analyzer

          image: 804540872991.dkr.ecr.ap-northeast-2.amazonaws.com/miniproject-management/document-analyzer:latest

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: document-analyzer-config

          env:
            - name: AWS_REGION
              value: ap-northeast-2

            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: S3_BUCKET_NAME

          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"

            limits:
              memory: "1Gi"
              cpu: "1000m"

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 20